"""财务数据表"""

from sqlalchemy import Column, DateTime, Float, Index, String, func

from app.database import Base


class StockFinancial(Base):
    __tablename__ = "stock_financial"

    ts_code = Column(String(20), primary_key=True, comment="股票代码")
    ann_date = Column(String(8), primary_key=True, comment="公告日期")
    end_date = Column(String(8), primary_key=True, comment="报告期截止日")
    eps = Column(Float, nullable=True)
    dt_eps = Column(Float, nullable=True)
    total_revenue_ps = Column(Float, nullable=True)
    revenue_ps = Column(Float, nullable=True)
    capital_rese_ps = Column(Float, nullable=True)
    surplus_rese_ps = Column(Float, nullable=True)
    undist_profit_ps = Column(Float, nullable=True)
    bps = Column(Float, nullable=True)
    ocfps = Column(Float, nullable=True)
    retainedps = Column(Float, nullable=True)
    cfps = Column(Float, nullable=True)
    ebit_ps = Column(Float, nullable=True)
    fcff_ps = Column(Float, nullable=True)
    fcfe_ps = Column(Float, nullable=True)
    diluted2_eps = Column(Float, nullable=True)
    profit_dedt = Column(Float, nullable=True, comment="扣非归母净利润（元）")
    revenue = Column(Float, nullable=True, comment="营业收入（元）")
    extra_item = Column(Float, nullable=True)
    gross_margin = Column(Float, nullable=True)
    op_income = Column(Float, nullable=True)
    valuechange_income = Column(Float, nullable=True)
    interst_income = Column(Float, nullable=True)
    daa = Column(Float, nullable=True)
    ebit = Column(Float, nullable=True)
    ebitda = Column(Float, nullable=True)
    fcff = Column(Float, nullable=True)
    fcfe = Column(Float, nullable=True)
    retained_earnings = Column(Float, nullable=True)
    netprofit_margin = Column(Float, nullable=True)
    grossprofit_margin = Column(Float, nullable=True)
    cogs_of_sales = Column(Float, nullable=True)
    expense_of_sales = Column(Float, nullable=True)
    profit_to_gr = Column(Float, nullable=True)
    saleexp_to_gr = Column(Float, nullable=True)
    adminexp_to_gr = Column(Float, nullable=True)
    finaexp_to_gr = Column(Float, nullable=True)
    impai_ttm = Column(Float, nullable=True)
    gc_of_gr = Column(Float, nullable=True)
    op_of_gr = Column(Float, nullable=True)
    ebit_of_gr = Column(Float, nullable=True)
    roe = Column(Float, nullable=True)
    roe_waa = Column(Float, nullable=True)
    roe_dt = Column(Float, nullable=True)
    roa = Column(Float, nullable=True)
    npta = Column(Float, nullable=True)
    roic = Column(Float, nullable=True)
    roe_yearly = Column(Float, nullable=True)
    roa2_yearly = Column(Float, nullable=True)
    roe_avg = Column(Float, nullable=True)
    opincome_of_ebt = Column(Float, nullable=True)
    investincome_of_ebt = Column(Float, nullable=True)
    n_op_profit_of_ebt = Column(Float, nullable=True)
    tax_to_ebt = Column(Float, nullable=True)
    dtprofit_to_profit = Column(Float, nullable=True)
    invturn_days = Column(Float, nullable=True)
    arturn_days = Column(Float, nullable=True)
    inv_turn = Column(Float, nullable=True)
    ar_turn = Column(Float, nullable=True)
    ca_turn = Column(Float, nullable=True)
    fa_turn = Column(Float, nullable=True)
    assets_turn = Column(Float, nullable=True)
    current_ratio = Column(Float, nullable=True)
    quick_ratio = Column(Float, nullable=True)
    cash_ratio = Column(Float, nullable=True)
    debt_to_assets = Column(Float, nullable=True)
    assets_to_eqt = Column(Float, nullable=True)
    dp_assets_to_eqt = Column(Float, nullable=True)
    ca_to_assets = Column(Float, nullable=True)
    nca_to_assets = Column(Float, nullable=True)
    tbassets_to_totalassets = Column(Float, nullable=True)
    int_to_talcap = Column(Float, nullable=True)
    eqt_to_talcap = Column(Float, nullable=True)
    currentdebt_to_debt = Column(Float, nullable=True)
    longdeb_to_debt = Column(Float, nullable=True)
    ocf_to_shortdebt = Column(Float, nullable=True)
    eqt_to_debt = Column(Float, nullable=True)
    eqt_to_interestdebt = Column(Float, nullable=True)
    tangibleasset_to_debt = Column(Float, nullable=True)
    tangibleasset_to_netdebt = Column(Float, nullable=True)
    ocf_to_debt = Column(Float, nullable=True)
    ocf_to_interestdebt = Column(Float, nullable=True)
    ocf_to_capitalexp = Column(Float, nullable=True)
    cash_to_currentliab = Column(Float, nullable=True)
    current_exint = Column(Float, nullable=True)
    noncurrent_exint = Column(Float, nullable=True)
    interestdebt = Column(Float, nullable=True)
    netdebt = Column(Float, nullable=True)
    tangible_asset = Column(Float, nullable=True)
    working_capital = Column(Float, nullable=True)
    networking_capital = Column(Float, nullable=True)
    invest_capital = Column(Float, nullable=True)
    salescash_to_or = Column(Float, nullable=True)
    ocf_to_or = Column(Float, nullable=True)
    ocf_to_opincome = Column(Float, nullable=True)
    capitalized_to_da = Column(Float, nullable=True)
    update_flag = Column(String(1), nullable=True)
    updated_at = Column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("ix_financial_code", "ts_code"),
        Index("ix_financial_end_date", "end_date"),
    )
