"""v2_watchlist_tables

Revision ID: 0127a57fdd13
Revises: ac271c65f3b7
Create Date: 2026-04-05 16:08:26.545449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0127a57fdd13'
down_revision: Union[str, Sequence[str], None] = 'ac271c65f3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分组名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分组说明'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序，数字越小越靠前'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所属分组'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码，如 000001.SZ'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='备注（为什么关注这只股票）'),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='加入时间'),
    sa.ForeignKeyConstraint(['group_id'], ['watchlist_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'ts_code', name='uq_group_stock')
    )
    op.create_index('ix_ws_code', 'watchlist_stock', ['ts_code'], unique=False)
    op.create_index('ix_ws_group', 'watchlist_stock', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_group', table_name='watchlist_stock')
    op.drop_index('ix_ws_code', table_name='watchlist_stock')
    op.drop_table('watchlist_stock')
    op.drop_table('watchlist_group')
    # ### end Alembic commands ###
