"""V1_初始表结构

Revision ID: ac271c65f3b7
Revises: 
Create Date: 2026-04-05 10:14:00.198651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac271c65f3b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('code', sa.String(length=50), nullable=False, comment='条件代码，如 amount_gt（程序内部用）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='条件名称（给用户看的）'),
    sa.Column('category', sa.String(length=30), nullable=True, comment='分类：量价/市值/技术/基本面/排名'),
    sa.Column('description', sa.Text(), nullable=True, comment='条件说明'),
    sa.Column('param_schema', sa.Text(), nullable=True, comment='参数定义（JSON）'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='策略名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略说明'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('condition_code', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=True, comment='参数值（JSON），覆盖条件默认值'),
    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='在本策略中是否启用此条件'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='条件执行顺序'),
    sa.ForeignKeyConstraint(['condition_code'], ['condition.code'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sc_strategy', 'strategy_condition', ['strategy_id'], unique=False)
    op.create_table('strategy_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True, comment='运行时的策略名称快照'),
    sa.Column('trade_date', sa.String(length=8), nullable=True, comment='筛选的交易日期 YYYYMMDD'),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='实际运行时间'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='筛出的股票数量'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时（毫秒）'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_date', 'strategy_run', ['trade_date'], unique=False)
    op.create_index('ix_run_strategy', 'strategy_run', ['strategy_id'], unique=False)
    op.create_table('screening_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='本次筛选中的排名'),
    sa.Column('snapshot', sa.Text(), nullable=True, comment='当时的关键数据快照（JSON）'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_result_code', 'screening_result', ['ts_code'], unique=False)
    op.create_index('ix_result_run', 'screening_result', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_result_run', table_name='screening_result')
    op.drop_index('ix_result_code', table_name='screening_result')
    op.drop_table('screening_result')
    op.drop_index('ix_run_strategy', table_name='strategy_run')
    op.drop_index('ix_run_date', table_name='strategy_run')
    op.drop_table('strategy_run')
    op.drop_index('ix_sc_strategy', table_name='strategy_condition')
    op.drop_table('strategy_condition')
    op.drop_table('strategy')
    op.drop_table('condition')
    # ### end Alembic commands ###
